### ISSUE TITLE
Gagal Sign Up

### ISSUE THREAD

**Issue by rigold** [2018-PemrogramanWeb-B/tugas7-fp-k-people#1]
![capture](https://user-images.githubusercontent.com/17819067/50201684-9cf3b480-038d-11e9-8134-86919f55605a.PNG)

Sign Up gagal,
kalau bisa mohon disertakan file sql nya juga, agar bisa mengakses database dari websitenya,

**Comment by atikakiki** [comment]
terima kasih, file sql sudah diupload, bisa dicoba ulang :)
