### ISSUE TITLE
Tampilan kurang maksimal (Menu,Contact dan lainnya)

### ISSUE THREAD

**Issue by cyber12drago** [2018-PemrogramanWeb-B/tugas7-fp-k-people#2]
Tampilan menu,contact dan lainnya kurang jelas. Dan belum ada DB
![kp](https://user-images.githubusercontent.com/36811855/50210657-501dd700-03a9-11e9-8fa9-58328645eeb2.jpg)
![kp2](https://user-images.githubusercontent.com/36811855/50210665-5449f480-03a9-11e9-9c80-a9de3f90ca42.jpg)
![kp3](https://user-images.githubusercontent.com/36811855/50210667-5613b800-03a9-11e9-8fdc-2ec537754ad4.jpg)

**Comment by cluster777** [comment]
![image](https://user-images.githubusercontent.com/42055002/50218294-fffd3f80-03bd-11e9-93ef-1bca309ab242.png)
tambahan untuk penglihatan di screen size width<=991px

**Comment by atikakiki** [comment]
fixed
