### ISSUE TITLE
Login.php

### ISSUE THREAD

**Issue by cyber12drago** [2018-PemrogramanWeb-B/tugas7-fp-k-people#3]
1. Saat Login gagal, akan muncul seperti ini. (saya tidak mencoba jika login berhasil karena regis tidak berhasil juga)
![login gagal](https://user-images.githubusercontent.com/36811855/50218014-122aae00-03bd-11e9-8b6d-6e312fcba53f.jpg)

2. Saat menekan tombol navbar(komunitas/event) di login php maka akan menuju ke bagian #log-in. Jika memang pengaturannya seperti itu harap diberitahukan.

**Comment by atikakiki** [comment]
database sudah diupload, bisa dicoba lagi, untuk yang nomer 2, memang di redirect ke #log-in jika user belum melakukan login. terima kasih :)
