### ISSUE TITLE
404 object not found

### ISSUE THREAD

**Issue by gslayer0** [2018-PemrogramanWeb-B/tugas7-fp-k-people#4]
![image](https://user-images.githubusercontent.com/37019764/50228606-f59d6e80-03da-11e9-97fc-10e39ff13084.png)

**Comment by gslayer0** [comment]
hal tersebut terjadi ketika selesai daftar

**Comment by atikakiki** [comment]
fixed. Jika Sign up berhasil, maka akan di redirect ke login.php
