### ISSUE TITLE
Contact-person dan email

### ISSUE THREAD

**Issue by cyber12drago** [2018-PemrogramanWeb-B/tugas7-fp-k-people#5]
Contact person bisa diisi dengan huruf lalu saat submit form apabila salah dalam pengisian email dan nomor telpon maka akan dianggap berhasil.

![kpop](https://user-images.githubusercontent.com/36811855/50230172-bd982a80-03de-11e9-83ea-6c13f9c3aa66.jpg)

**Comment by atikakiki** [comment]
fixed, sudah diedit.
untuk email sudah diperbaiki, jika pengisian tidak sesuai format, maka tidak akan diterima.
untuk cp memang diisi sesuai keperluan, bisa nomer atau huruf, karena cp yang dimaksud adalah nama dan nomor.
